### ISSUE TITLE
list index error while using Mordred

### ISSUE THREAD

**Issue by vaibhavadixit** [mordred-descriptor/mordred#74]
description
I am facing the following error trying to use Mordred in anaconda prompt.
The module was working fine last week and I did generate expected ouput.csv files with descriptors, but it is now giving the error given below.
The test job is also giving some errors (given below).
Can you please take a look and suggest me how to fix these errors?
Thank you and regards
Dr. Vaibhav A. Dixit,
Assistant Professor,
Department of Pharmacy,
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
Birla Institute of Technology and Sciences Pilani (BITS-Pilani),
VidyaVihar Campus, street number 41, 
Pilani, 333031, Rajasthan. India 
Phone No. +91 1596 255652, Mob. No. +91-7709129400,
Email: vaibhav.dixit@pilani.bits-pilani.ac.in, vaibhavadixit@gmail.com
​http://www.bits-pilani.ac.in/pilani/vaibhavdixit/profile
https://www.linkedin.com/in/vaibhav-dixit-b1a07a39/
ORCID ID: https://orcid.org/0000-0003-4015-2941
http://scholar.google.co.in/citations?user=X876BKcAAAAJ&hl=en&oi=sra

minimal reproduction code
--

Please fill me if possible.

environment

### OS/distribution
windows
Please fill me.

### conda or pip
conda
Please choose conda or pip.

### python version
Python 3.6.7 |Anaconda custom (64-bit)| (default, Oct 28 2018, 19:44:12) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
Please execute the command and paste result.

```.bash
python --version
```

### library version

Please execute the command and paste result.

(base) C:\Users\user\Vaibhav>python -m mordred -o output.csv CYP3A4-inhi-active-notactive.smi -3 -v
Traceback (most recent call last):
  File "C:\Users\user\PyMOL\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\PyMOL\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\PyMOL\lib\site-packages\mordred\__main__.py", line 203, in <module>
    main()
  File "C:\Users\user\PyMOL\lib\site-packages\mordred\__main__.py", line 197, in main
    descriptor=p.descriptor, with3D=p.with3D, verbosity=p.verbosity,
  File "C:\Users\user\PyMOL\lib\site-packages\mordred\__main__.py", line 125, in main_process
    mols = list(mols)
  File "C:\Users\user\PyMOL\lib\site-packages\mordred\__main__.py", line 117, in <genexpr>
    mols = (m for i in input for m in parser(i))
  File "C:\Users\user\PyMOL\lib\site-packages\mordred\__main__.py", line 66, in auto_parser
    for m in r:
  File "C:\Users\user\PyMOL\lib\site-packages\mordred\__main__.py", line 26, in smiles_parser
    smi = line[0]
IndexError: list index out of range

Test jobs errors:
(base) C:\Users\user\Vaibhav>python -m mordred.tests
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................E.........................E.............................................................................................................................
.........................................................................................................................................................................................................E....
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'yaml')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\user\PyMOL\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\Users\user\PyMOL\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\PyMOL\lib\site-packages\mordred\tests\test_by_references.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

======================================================================
ERROR: Failure: ImportError (cannot import name 'AbstractMethodError')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\user\PyMOL\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\Users\user\PyMOL\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\PyMOL\lib\site-packages\mordred\tests\test_pandas.py", line 5, in <module>
    from mordred._base.pandas_module import MordredDataFrame
  File "C:\Users\user\PyMOL\lib\site-packages\mordred\_base\pandas_module.py", line 2, in <module>
    from pandas import Series, DataFrame
  File "C:\Users\user\PyMOL\lib\site-packages\pandas\__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "C:\Users\user\PyMOL\lib\site-packages\pandas\core\api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "C:\Users\user\PyMOL\lib\site-packages\pandas\core\groupby\__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "C:\Users\user\PyMOL\lib\site-packages\pandas\core\groupby\groupby.py", line 48, in <module>
    from pandas.core.arrays import ExtensionArray, Categorical
  File "C:\Users\user\PyMOL\lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from .base import ExtensionArray  # noqa
  File "C:\Users\user\PyMOL\lib\site-packages\pandas\core\arrays\base.py", line 10, in <module>
    from pandas.errors import AbstractMethodError
ImportError: cannot import name 'AbstractMethodError'

======================================================================
ERROR: Failure: ImportError (cannot import name 'AbstractMethodError')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\user\PyMOL\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\Users\user\PyMOL\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\PyMOL\lib\site-packages\mordred\_base\pandas_module.py", line 2, in <module>
    from pandas import Series, DataFrame
  File "C:\Users\user\PyMOL\lib\site-packages\pandas\__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "C:\Users\user\PyMOL\lib\site-packages\pandas\core\api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "C:\Users\user\PyMOL\lib\site-packages\pandas\core\groupby\__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "C:\Users\user\PyMOL\lib\site-packages\pandas\core\groupby\groupby.py", line 48, in <module>
    from pandas.core.arrays import ExtensionArray, Categorical
  File "C:\Users\user\PyMOL\lib\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from .base import ExtensionArray  # noqa
  File "C:\Users\user\PyMOL\lib\site-packages\pandas\core\arrays\base.py", line 10, in <module>
    from pandas.errors import AbstractMethodError
ImportError: cannot import name 'AbstractMethodError'

----------------------------------------------------------------------
Ran 61286 tests in 60.156s

FAILED (errors=3)

* conda

    ```.bash
    conda list
    ```
(base) C:\Users\user\Vaibhav>conda list
# packages in environment at C:\Users\user\PyMOL:
#
# Name                    Version                   Build  Channel
anaconda                  custom           py36h363777c_0
anyqt                     0.0.10                   py36_0
apbs                      1.5                           1    schrodinger
asn1crypto                0.24.0                   py36_0
babel                     2.6.0                    pypi_0    pypi
base58                    1.0.3                    pypi_0    pypi
blas                      1.0                         mkl
bottleneck                1.2.1            py36h452e1ab_1
ca-certificates           2019.1.23                     0
cachecontrol              0.12.5                   pypi_0    pypi
cairo                     1.14.12              hf171d8a_3
certifi                   2019.3.9                 py36_0
cffi                      1.11.5           py36h74b6da3_1
chardet                   3.0.4                    py36_1
cloudpickle               0.8.0                    pypi_0    pypi
conda                     4.6.8                    py36_0
conda-env                 2.6.0                h36134e3_1
console_shortcut          0.1.1                h6bb2dd7_3
cryptography              2.3.1            py36h74b6da3_0
cycler                    0.10.0           py36h009560c_0
decorator                 4.3.2                    py36_0
docutils                  0.14             py36h6012d8f_0
entrypoints               0.3                      py36_0
et-xmlfile                1.0.1                    pypi_0    pypi
fasttsne                  0.2.13           py36h8c2d366_1
freemol                   1.158                    py36_1    schrodinger
freetype                  2.9.1                ha9979f8_1
gitdb2                    2.0.5                    pypi_0    pypi
gitpython                 2.1.11                   pypi_0    pypi
glew                      2.0.0                         0    schrodinger
grep                      0.3.2                    pypi_0    pypi
h2                        2.6.2                    pypi_0    pypi
h5py                      2.8.0            py36h3bdd7fb_2
hdf5                      1.10.2               hac2f561_1
hpack                     3.0.0                    pypi_0    pypi
hyper                     0.7.0                    pypi_0    pypi
hyperframe                3.2.0                    pypi_0    pypi
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py36_0
intel-openmp              2018.0.3                      0
jdcal                     1.4                      pypi_0    pypi
joblib                    0.13.2                   py36_0
jpeg                      9b                   hb83a4c4_2
keyring                   18.0.0                   py36_0
keyrings.alt              3.1.1                    py36_0
kiwisolver                1.0.1            py36h6538335_0
libboost                  1.67.0               hd9e427e_4
libiconv                  1.15                 h1df5818_7
libpng                    1.6.34               h79bbb47_0
libtiff                   4.0.9                h36446d0_2
libxml2                   2.9.8                hadb2253_1
linecache2                1.0.0                    py36_0
llvmlite                  0.27.0           py36ha925a31_0
loky                      2.4.2                    pypi_0    pypi
makeportable              1.0                           3    schrodinger
matplotlib                2.2.2            py36had4c4a9_2
mengine                   1                             0    schrodinger
menuinst                  1.4.14           py36hfa6e2cd_0
mkl                       2018.0.3                      1
mkl_fft                   1.0.6            py36hdbbee80_0
mkl_random                1.0.1            py36h77b88f5_1
mordred                   1.1.1            py36h39e3cac_0    mordred-descriptor
mordred-web               0.3.4                    pypi_0    pypi
mpeg_encode               1                             0    schrodinger
msgpack-python            0.5.6            py36he980bc4_1
mtz2ccp4_px               1.0                           1    schrodinger
networkx                  2.2                      py36_1
normalize                 1.0.4                    pypi_0    pypi
numba                     0.42.0           py36hf9181ef_0
numpy                     1.15.4           py36ha559c80_0
numpy-base                1.15.4           py36h8128ebf_0
olefile                   0.46                     py36_0
openpyxl                  2.6.0                    pypi_0    pypi
openssl                   1.0.2r               he774522_0
orange3                   3.19.0           py36ha925a31_0
orange3-chemoinformatics  0.1.0                    pypi_0    pypi
pandas                    0.22.0                   pypi_0    pypi
pdb2pqr                   2.1.1                    py36_1    schrodinger
pillow                    5.2.0            py36h08bbbbd_0
pip                       19.0.3                   pypi_0    pypi
pixman                    0.34.0               hcef7cb0_3
pmw                       2.0.1                    py36_2    schrodinger
psutil                    5.5.1                    pypi_0    pypi
py-boost                  1.67.0           py36h8300f20_4
pycosat                   0.6.3            py36hfa6e2cd_0
pycparser                 2.19                     py36_0
pydpi                     1.0                      pypi_0    pypi
pymol                     2.3.0                    py36_0    schrodinger
pymol-upgrade-helper      1.0                           1    schrodinger
pymol-web-examples        2.0                           2    schrodinger
pymol-web-legacy          2.0                        py_1    schrodinger
pyopenssl                 19.0.0                   py36_0
pyparsing                 2.3.1                    py36_0
pyqt                      5.6.0            py36ha878b3d_6
pyqtgraph                 0.10.0           py36h28b3542_3
pysocks                   1.6.8                    py36_0
python                    3.6.7                h33f27b4_1
python-dateutil           2.7.5                    py36_0
python-louvain            0.11             py36h28b3542_0
pytz                      2018.9                   py36_0
pywin32                   223              py36hfa6e2cd_1
qt                        5.6.2           vc14h6f8c307_12
rdkit                     2018.09.2.0      py36h07f3614_1    rdkit
requests                  2.21.0                   py36_0
richenum                  1.2.1                    pypi_0    pypi
rigimol                   1.3                           2    schrodinger
ruamel_yaml               0.15.46          py36hfa6e2cd_0
scikit-learn              0.20.2                   pypi_0    pypi
scipy                     1.2.1                    pypi_0    pypi
serverfiles               0.3.0                    py36_0
setuptools                40.7.3                   py36_0
simplemmtf-python         0.2                           0    schrodinger
sip                       4.18.1           py36h6538335_2
six                       1.12.0                   py36_0
sklearn                   0.0                      pypi_0    pypi
smmap2                    2.0.5                    pypi_0    pypi
sqlite                    3.25.2               hfa6e2cd_0
tk                        8.6.8                hfa6e2cd_0
tornado                   5.1.1            py36hfa6e2cd_0
tqdm                      4.31.1                     py_0
traceback2                1.4.0                    py36_0
unique                    0.1                      pypi_0    pypi
unittest2                 1.1.0                    py36_0
urllib3                   1.24.1                   py36_0
vc                        14.1                 h0510ff6_4
vs2008_runtime            9.00.30729.5054               0
vs2013_runtime            12.0.21005                    1
vs2015_runtime            14.15.26706          h3a45250_0
wheel                     0.32.3                   py36_0
win_inet_pton             1.0.1                    py36_1
win_unicode_console       0.5              py36hcdbd4b5_0
wincertstore              0.2              py36h7fe50ca_0
xlrd                      1.2.0                    py36_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zlib                      1.2.11               h8395fce_2

* pip

    ```.bash
    python -m pip list
    python -c 'import rdkit; print("rdkit " + rdkit.__version__)'
    ```
(base) C:\Users\user\Vaibhav> python -m pip list
Package                  Version
------------------------ --------
AnyQt                    0.0.10
asn1crypto               0.24.0
Babel                    2.6.0
backcall                 0.1.0
base58                   1.0.3
bleach                   3.0.2
Bottleneck               1.2.1
CacheControl             0.12.5
certifi                  2019.3.9
cffi                     1.11.5
chardet                  3.0.4
cloudpickle              0.8.0
colorama                 0.4.0
conda                    4.6.8
cryptography             2.3.1
cycler                   0.10.0
decorator                4.3.0
defusedxml               0.5.0
docutils                 0.14
entrypoints              0.2.3
et-xmlfile               1.0.1
fastTSNE                 0.2.13
freemol                  1.158
gitdb2                   2.0.5
GitPython                2.1.11
grep                     0.3.2
h2                       2.6.2
h5py                     2.8.0
hpack                    3.0.0
hyper                    0.7.0
hyperframe               3.2.0
idna                     2.8
ipykernel                5.1.0
ipython                  7.1.1
ipython-genutils         0.2.0
ipywidgets               7.4.2
jdcal                    1.4
jedi                     0.13.1
Jinja2                   2.10
joblib                   0.13.2
jsonschema               2.6.0
jupyter                  1.0.0
jupyter-client           5.2.3
jupyter-console          6.0.0
jupyter-core             4.4.0
keyring                  18.0.0
keyrings.alt             3.1.1
kiwisolver               1.0.1
linecache2               1.0.0
llvmlite                 0.27.0
loky                     2.4.2
MarkupSafe               1.1.0
matplotlib               3.0.2
menuinst                 1.4.14
mistune                  0.8.4
mkl-fft                  1.0.6
mkl-random               1.0.1
mordred                  1.1.1
mordred-web              0.3.4
mpmath                   1.0.0
msgpack                  0.5.6
nbconvert                5.4.0
nbformat                 4.4.0
networkx                 2.2
normalize                1.0.4
nose                     1.3.7
notebook                 5.7.2
numba                    0.42.0
numpy                    1.15.4
olefile                  0.46
openpyxl                 2.6.0
Orange3                  3.19.0
Orange3-Chemoinformatics 0.1.0
pandas                   0.23.4
pandocfilters            1.4.2
parso                    0.3.1
pdb2pqr-minimal          0.0.0
pickleshare              0.7.5
Pillow                   5.2.0
pip                      19.0.3
prometheus-client        0.4.2
prompt-toolkit           2.0.7
psutil                   5.5.1
pycosat                  0.6.3
pycparser                2.19
pydpi                    1.0
Pygments                 2.2.0
pymol                    2.3.0
pyOpenSSL                19.0.0
pyparsing                2.3.0
pyqtgraph                0.10.0
PySocks                  1.6.8
python-dateutil          2.7.5
python-louvain           0.11
pytz                     2018.7
pywin32                  223
pywinpty                 0.5.4
pyzmq                    17.1.2
qtconsole                4.4.3
requests                 2.21.0
richenum                 1.2.1
ruamel-yaml              0.15.46
scikit-learn             0.20.2
scipy                    1.1.0
Send2Trash               1.5.0
serverfiles              0.3.0
setuptools               40.7.3
six                      1.11.0
sklearn                  0.0
smmap2                   2.0.5
sympy                    1.3
terminado                0.8.1
testpath                 0.4.2
tornado                  5.1.1
tqdm                     4.31.1
traceback2               1.4.0
traitlets                4.3.2
unique                   0.1
unittest2                1.1.0
urllib3                  1.24.1
wcwidth                  0.1.7
webencodings             0.5.1
wheel                    0.32.3
widgetsnbextension       3.4.2
win-inet-pton            1.0.1
win-unicode-console      0.5
wincertstore             0.2
xlrd                     1.2.0

(base) C:\Users\user\Vaibhav>python
Python 3.6.7 |Anaconda custom (64-bit)| (default, Oct 28 2018, 19:44:12) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import rdkit
>>> print("rdkit" + rdkit.__version__)
rdkit2018.09.2
>>>

**Comment by philopon** [comment]
I appreciate your thoughtful report.

It seems loads pandas included in PyMOL instead of conda package.
Please check your PATH environment variable?

```
python -c 'import sys; [print(p) for p in sys.path]'
```

And, please check PYTHONPATH environment variable when `C:\Users\user\PyMOL\lib\site-packages` is found.

```
python -c 'import os; print(os.environ.get("PYTHONPATH"))'
```

Thanks,

**Comment by porteusconf** [comment]
You are missing pyyaml
I also had similar nose and yaml errors fixed in miniconda3 by  ```conda install nose pyyaml```
