### ISSUE TITLE
Installation DOWNGRADES a lot of packages

### ISSUE THREAD

**Issue by gmseabra** [mordred-descriptor/mordred#75]
Hi, 
Trying to install Mordred in my system here, but it seems to have very strict dependencies, and is trying to downgrade a huge number of packages in my installation:
--
`conda install -c rdkit -c mordred-descriptor Mordred`
... Tries to uninstall >20 packages from my system, and downgrade > 70 packages. 

Please see the attached file [Mordred_install.txt](https://github.com/mordred-descriptor/mordred/files/3149785/Mordred_install.txt) for a full output.

I would guess it is related to requiring the downgrade of Python itself:
``` 
The following packages will be DOWNGRADED:

...
python                                   3.7.3-h8c8aaf0_0 --> 3.6.8-h9f7ef89_7
...
```

Is this really necessary? Is it possible to install Mordred without such huge change in my environment?

Thanks!

environment
--
### OS/distribution

Windows 10 Home 64bits  1809 

### conda or pip

Conda (Miniconda) version 4.6.14

### python version

python 3.7.3

### library version

Please execute the command and paste result.

* conda

```
> conda list

# packages in environment at C:\Users\gmseabra\Miniconda3\envs\unc:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl
absl-py                   0.7.0                    py37_0
asn1crypto                0.24.0                   py37_0
astor                     0.7.1                    py37_0
astroid                   2.2.5                    py37_0
attrs                     19.1.0                   py37_1
backcall                  0.1.0                    py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
boost                     1.68.0          py37hf75dd32_1001    conda-forge
boost-cpp                 1.68.0            h6a4c333_1000    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.16.0            hc1b38c8_1000    conda-forge
certifi                   2019.3.9                 py37_0
cffi                      1.12.3           py37h7a1dbc1_0
chardet                   3.0.4                    py37_1
colorama                  0.4.1                    py37_0
console_shortcut          0.1.1                         3
cryptography              2.6.1            py37h7a1dbc1_0
cudatoolkit               10.0.130                      0
cycler                    0.10.0                   py37_0
decorator                 4.4.0                    py37_1
defusedxml                0.5.0                    py37_1
entrypoints               0.3                      py37_0
freetype                  2.9.1                ha9979f8_1
gast                      0.2.2                    py37_0
grpcio                    1.16.1           py37h351948d_1
h5py                      2.9.0            py37h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
intel-openmp              2019.3                      203
ipykernel                 5.1.0            py37h39e3cac_0
ipython                   7.4.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.4.2                    py37_0
isort                     4.3.17                   py37_0
jedi                      0.13.3                   py37_0
jinja2                    2.10.1                   py37_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.0.1                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.2.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py37_0    conda-forge
jupyter_core              4.4.0                    py37_0
jupyter_highlight_selected_word 0.2.0                 py37_1000    conda-forge
jupyter_latex_envs        1.4.4                 py37_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
jupyterthemes             0.20.0                   pypi_0    pypi
keras-applications        1.0.7                      py_0
keras-preprocessing       1.0.9                      py_0
kiwisolver                1.0.1            py37h6538335_0
lazy-object-proxy         1.3.1            py37hfa6e2cd_2
lesscpy                   0.13.0                   pypi_0    pypi
libiconv                  1.15                 h1df5818_7
libmklml                  2019.0.3                      0
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.6.1                h7bd577a_0
libsodium                 1.0.16               h9d3ae62_0
libtiff                   4.0.10               hb898794_2
libxml2                   2.9.9                h464c3ec_0
libxslt                   1.1.33               h579f668_0
lxml                      4.3.3            py37h1350720_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.0.1                    py37_0
markupsafe                1.1.1            py37he774522_0
matplotlib                3.0.3            py37hc8f65d3_0
mccabe                    0.6.1                    py37_1
menuinst                  1.4.16           py37he774522_0
mistune                   0.8.4            py37he774522_0
mkl                       2019.3                      203
mkl_fft                   1.0.10           py37h14836fe_0
mkl_random                1.0.2            py37h343c172_0
mock                      2.0.0                    py37_0
molvs                     0.1.1                      py_0    conda-forge
msys2-conda-epoch         20160418                      1
nbconvert                 5.4.1                    py37_3
nbformat                  4.4.0                    py37_0
ninja                     1.9.0            py37h74a9793_0
notebook                  5.7.8                    py37_0
numpy                     1.16.3           py37h19fb1c0_0
numpy-base                1.16.3           py37hc3f5095_0
olefile                   0.46                     py37_0
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
pandas                    0.24.2           py37ha925a31_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parso                     0.4.0                      py_0
patsy                     0.5.1                    py37_0
pbr                       5.1.3                      py_0
pickleshare               0.7.5                    py37_0
pillow                    6.0.0            py37hdc69c19_0
pip                       19.0.3                   py37_0
pixman                    0.34.0               hcef7cb0_3
ply                       3.11                     pypi_0    pypi
prometheus_client         0.6.0                    py37_0
prompt_toolkit            2.0.9                    py37_0
protobuf                  3.6.1            py37h33f27b4_0
pubchempy                 1.0.4                      py_2    mcs07
pycairo                   1.18.1           py37h63da52a_0
pycosat                   0.6.3            py37hfa6e2cd_0
pycparser                 2.19                     py37_0
pygments                  2.3.1                    py37_0
pylint                    2.3.1                    py37_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.4.0                      py_0
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyrsistent                0.14.11          py37he774522_0
pysocks                   1.6.8                    py37_0
python                    3.7.3                h8c8aaf0_0
python-dateutil           2.8.0                    py37_0
pytorch-nightly           1.0.0.dev20190401 py3.7_cuda100_cudnn7_0    pytorch
pytz                      2019.1                     py_0
pywin32                   223              py37hfa6e2cd_1
pywinpty                  0.5.5                 py37_1000
pyyaml                    5.1              py37he774522_0
pyzmq                     18.0.0           py37ha925a31_0
qt                        5.9.7            vc14h73c81de_0
qtconsole                 4.4.3                    py37_0
rdkit                     2018.09.1       py37h3020836_1001    conda-forge
requests                  2.21.0                   py37_0
ruamel_yaml               0.15.46          py37hfa6e2cd_0
scikit-learn              0.20.3           py37h343c172_0
scipy                     1.2.1            py37h29ff71c_0
seaborn                   0.9.0                    py37_0
send2trash                1.5.0                    py37_0
setuptools                41.0.0                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.12.0                   py37_0
sqlite                    3.28.0               he774522_0
statsmodels               0.9.0            py37h452e1ab_0
tensorboard               1.13.1                   py37_0    conda-forge
tensorflow                1.13.1          mkl_py37h9463c59_0
tensorflow-base           1.13.1          mkl_py37hcaf7020_0
tensorflow-estimator      1.13.0           py37h39e3cac_0    conda-forge
termcolor                 1.1.0                    py37_1
terminado                 0.8.2                    py37_0
testpath                  0.4.2                    py37_0
tk                        8.6.8                hfa6e2cd_0
tornado                   6.0.2            py37he774522_0
tqdm                      4.31.1                   py37_1
traitlets                 4.3.2                    py37_0
urllib3                   1.24.1                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.15.2                     py_0
wheel                     0.33.1                   py37_0
widgetsnbextension        3.4.2                    py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.1           py37he774522_0
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zeromq                    4.3.1                h33f27b4_3
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0

```

**Comment by philopon** [comment]
Thank you for your report!

It is unnecessary downgrade as you said.

Since current build system is created before noarch (https://www.anaconda.com/condas-new-noarch-packages/) package was released, each package depends on specific version of python. And mordred package for python3.7 is not built.

I'll update build system when 1.2.0 is released.

I recommend create new environment until 1.2.0 released.

```
conda create -n mordred -c mordred-descriptor mordred
conda activate mordred
```

or, please use pip install.

```
pip install mordred
```

I'm sorry for your inconvenience but thank you for your cooperation.

Cheers,

**Comment by gmseabra** [comment]
Thank you!

Is there a timetable for the next release?

All the best!

**Comment by philopon** [comment]
Milestone of 1.2.0 can view in https://github.com/mordred-descriptor/mordred/milestone/5.

Unfortunately, I cannot tell you specific schedule because I'm pretty busy now.
However, since this issue is very high priority and independent with other updates, I consider 1.1.2 release to resolve only this issue.

Thanks,

**Comment by gmseabra** [comment]
Thank you,
> I recommend create new environment until 1.2.0 released.
> conda create -n mordred -c mordred-descriptor mordred
> conda activate mordred

As I'm trying to incorporate the descriptors calculation as part of a pipeline, having Mordred in a different environment is not really an option for me.

> or, please use pip install.
> pip install mordred

I used this. Pip install worked, with some restrictions:

1. When testing, it requires the extra package `nose`. Not a real problem, I could install that easily.
2. Testing fails in 4 cases. In all cases, the error message is the same: 
```
======================================================================
ERROR: Failure: ValueError (object must be a class or function)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gmseabra\Miniconda3\envs\unc\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\gmseabra\Miniconda3\envs\unc\lib\site-packages\nose\plugins\manager.py", line 154, in generate
    for r in result:
  File "C:\Users\gmseabra\Miniconda3\envs\unc\lib\site-packages\nose\plugins\doctests.py", line 228, in loadTestsFromModule
    tests = self.finder.find(module)
  File "C:\Users\gmseabra\Miniconda3\envs\unc\lib\doctest.py", line 932, in find
    self._find(tests, obj, name, module, source_lines, globs, {})
  File "C:\Users\gmseabra\Miniconda3\envs\unc\lib\doctest.py", line 993, in _find
    self._from_module(module, val)):
  File "C:\Users\gmseabra\Miniconda3\envs\unc\lib\doctest.py", line 966, in _from_module
    raise ValueError("object must be a class or function")
ValueError: object must be a class or function
```

3. When trying to use it, it does seem to work but with warnings:

```
>ipython
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from mordred import Calculator, descriptors
C:\Users\gmseabra\Miniconda3\envs\unc\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\gmseabra\Miniconda3\envs\unc\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\gmseabra\Miniconda3\envs\unc\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [2]: n_all = len(Calculator(descriptors, ignore_3D=False).descriptors)

In [3]: n_2D = len(Calculator(descriptors, ignore_3D=True).descriptors)

In [4]: print("2D:    {:5}\n3D:    {:5}\n------------\ntotal: {:5}".format(n_2D, n_all - n_2D, n_all))
2D:     1613
3D:      212
------------
total:  1825

In [5]: calc = Calculator(descriptors, ignore_3D=True)

In [6]: from rdkit import Chem

In [7]: mol = Chem.MolFromSmiles('c1ccccc1')

In [9]: calc(mol)
Out[9]: [snip] 
            (Prints a lot of info. 
            Note: many " <mordred.error.Missing object at 0x000001DDE9B409E8>")

In [10]: calc(mol)[:3]
Out[10]: [4.242640687119286, 3.9999999999999996, 0]

In [11]: mols = [Chem.MolFromSmiles(smi) for smi in ['c1ccccc1Cl', 'c1ccccc1O', 'c1ccccc1N']]

In [12]: df = calc.pandas(mols)
C:\Users\gmseabra\Miniconda3\envs\unc\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\gmseabra\Miniconda3\envs\unc\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  3.80it/s]

In [13]: df['SLogP']
Out[13]:
0    2.3400
1    1.3922
2    1.2688
Name: SLogP, dtype: float64
```

So, apparently it works (with warnings). Thanks!

**Comment by philopon** [comment]
Thank you for waiting. v1.2.0 is released!

https://github.com/mordred-descriptor/mordred/releases/tag/v1.2.0
