### ISSUE TITLE
Compatible conda modules missing form install.

### ISSUE THREAD

**Issue by diegoenry** [mordred-descriptor/mordred#92]
Summary
--
It's really easy to install with conda 👍 but there are missing instructions about compatible module versions.

Here is what I needed to complete "python -m mordred.tests" without errors.
conda install networkx=2.3
conda install pandas=0.25-3
conda install pyyaml

Now it's all fine, thanks for a great software !

Below is a sample of errors I had while running: python -m mordred.tests

# Yaml (not installed or "conda install yaml")
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'yaml')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dgomes/miniconda3/envs/mordred/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/dgomes/miniconda3/envs/mordred/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/dgomes/miniconda3/envs/mordred/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/dgomes/miniconda3/envs/mordred/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/dgomes/miniconda3/envs/mordred/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/dgomes/miniconda3/envs/mordred/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dgomes/miniconda3/envs/mordred/lib/python3.7/site-packages/mordred/tests/test_by_references.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

# Networkx 2.5
======================================================================
FAIL: mordred.tests.test_mordred_main.test_sdf_3D
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dgomes/miniconda3/envs/mordred/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/dgomes/miniconda3/envs/mordred/lib/python3.7/site-packages/mordred/tests/test_mordred_main.py", line 176, in test_sdf_3D
    eq_(stderr, "")
AssertionError: "[ERROR] Benzene: module 'networkx' has no attribute 'biconnected_component_subgraphs' (SpAbs_Dt/SpAbs/mordred._matrix_attributes.Eigen(mordred.DetourMatrix.DetourMatrixCache())/mordred.DetourMatrix.DetourMatrixCache())\n" != ''

# PANDAS 1.0.1
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  yield ok_, np.isnan(f.ix[1, 1])
./home/dgomes/miniconda3/envs/mordred/lib/python3.7/site-packages/mordred/tests/test_pandas.py:26: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

**Comment by plkx** [comment]
Fixes for all of these can be found in other Issues/threads.

The pandas issue is easily resolved as described in  https://github.com/mordred-descriptor/mordred/issues/80#issuecomment-718042620

PANDAS through version 1.1.3 can then be used.

The NETWORKX issue is resolved as described here: https://github.com/mordred-descriptor/mordred/issues/80#issuecomment-725330942

NETWORKX through version 2.5 can then be used.

You must install YAML.

Best Regards,

plkx
